#include <iostream>
#include <fstream>
#include "float_double_generated.h" // This was generated by `flatc`.

using namespace Sample; // Specified in the schema.

int main() {
    // output.bin ファイルをバイナリモードで読み込み
    std::ifstream infile("output.bin", std::ios::binary);
    if (!infile) {
        std::cerr << "Failed to open file for reading" << std::endl;
        return 1;
    }

    // ファイルの内容をバッファに読み込む
    infile.seekg(0, std::ios::end);
    size_t size = infile.tellg();
    infile.seekg(0, std::ios::beg);

    std::vector<uint8_t> buffer(size);
    infile.read(reinterpret_cast<char*>(buffer.data()), size);
    infile.close();

    // デシリアライズ処理
    auto toptable = GetTopTable(buffer.data());
    std::cout << "f_val: " << toptable->f_val() << std::endl;
    std::cout << "d_val: " << toptable->d_val() << std::endl;

    return 0;
}
