#include <iostream>
#include <fstream>
#include "float_double_generated.h" // This was generated by `flatc`.
 
using namespace Sample; // Specified in the schema.

int main()
{
    flatbuffers::FlatBufferBuilder builder;

    auto toptable = CreateTopTable(builder, 0.1, 0.1);

    builder.Finish(toptable);

    // バイナリファイルに書き出し
    std::ofstream outfile("output.bin", std::ios::binary);
    if (!outfile) {
        std::cerr << "Failed to open file for writing" << std::endl;
        return 1;
    }

    // FlatBuffersの GetBufferPointer 関数は uint8_t* 型のポインタを返す為、
    // std::ofstream::write 関数は const char* 型のポインタが必要
    // よって、reinterpret_cast<const char*>でキャストする
   outfile.write(reinterpret_cast<const char*>(builder.GetBufferPointer()), builder.GetSize());
    
}